//
// Created by cristobal on 6/2/21.
//

#ifndef RDFCACHEK2_NETWORK_MSG_DEFINITIONS_HPP
#define RDFCACHEK2_NETWORK_MSG_DEFINITIONS_HPP
#include <cstdint>

const size_t MAX_PROTO_MESSAGE_SIZE_ALLOWED = 500'000'000;

#endif // RDFCACHEK2_NETWORK_MSG_DEFINITIONS_HPP
